### ISSUE TITLE
Use direct image URLs instead of getSignedURL() for editon images

### ISSUE THREAD

**Issue by AndreasHaaversen** [readme-ntnu/readme-arkiv#27]
Right now, edition images URLs are fetched by Firebase using signed URLs. That works but has the unfortunate side-effect of not caching the images on the client.

Right now, about half a gig of bandwidth is used from Firebase storage in this project, seemingly mostly for these edition images.

The contents of those buckets are public (was made public for the Webkom abakus.no integration). It is, therefore, possible to fetch a direct URL, without signing it first. This will help with the caching problem and hopefully reduce the bandwidth used.

**Comment by AndreasHaaversen** [comment]
Det viser seg at å bruke direkte nedlastningsurl-er ikke hadde like god effekt som først forventet. Bruken av båndbredde er ca. like stor (varierer mellom 500mb til 1gb), så her må det litt mer arbeid til for å minimere bruken.

**Comment by draperunner** [comment]
Ser ut som at du kan resize bildene til å vere litt mindre.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/4339443/96159719-49186f00-0f15-11eb-90f9-9a4a4a59ba53.png">

Går òg an å bruke .webp-formatet som har mykje betre komprimering (men er ikkje støtta av Safari enno): https://developers.google.com/speed/webp/

[Sharp](https://sharp.pixelplumbing.com/) er ein nydeleg pakke for bildehandtering og støttar både resizing og webp-konvertering. Men eg veit ikkje om det funker i Firebase Functions out-of-the-box.

**Comment by AndreasHaaversen** [comment]
Kan melde at Sharp fungerer fint i Firebase Functions, vi bruker det allerede til å skalere forsidebildene våre til rett bredde 😁

Litt av utfordringen med bildebredde er at de fire siste utgavene vises på forsiden til abakus.no. Webkom klaget på den opprinnelige oppløsningen til forsidebildene, som var 200px brede. Den ble skrudd opp til nåværende nivå for at det skulle se bedre ut der. Akkuratt nå er det utgavene fra og med 06 2019 som har 620px bredde, resten skal ha 200px.

Jeg kan ta å eksperimentere litt med forskjellige størrelser for å finne et bedre kompromiss. Jeg tenker også å se om jeg klarer å spore kilden til datakonsumet litt bedre. Jeg lurer litt på om det kan være andre kilder til datakonsumet vi ser enn forsiden. Om alle bildene hadde vært 90kb, ville vi kunne forventet at antall unike brukere er maks 76, uten å ta høyde for nedlasting av PDF-ene som er betraktlig tyngre.

**Comment by AndreasHaaversen** [comment]
Kanskje det hadde vært en god ide å flytte uthenting av bilde og pdf url-ene til Functions? Da hadde det vært mulig å få bedre kontroll over cache-oppførselen og sørge for at det lagres i CDN også, iflg. [dokumentasjonen](https://firebase.google.com/docs/hosting/manage-cache)

**Comment by AndreasHaaversen** [comment]
Jeg har nå økt cache-levetiden i bucket-en ganske kraftig, til 6 timer. Det er kanskje litt overkill, men vi får se hvordan det påvriker nedlastningstallene våre.

**Comment by AndreasHaaversen** [comment]
Nedlastningstallene har vært ganske stabilt lave, så jeg tror vi kan la denne ligge inntill videre.

**Comment by AndreasHaaversen** [comment]
Fått et nytt innfall her: Bruke redirects i Firebase Hosting til å rute bildehenting til en Cloud function som svarer med faktisk bildedata istedenfor lenker, med lang cache-levetid. Da vil bildene faktisk lagres i cachen, ikke bare lenkene.

Ser de tidligere løsningene mine er preget av at jeg ikke forsto oppsettet helt, men dette tror jeg blir en mye bedre løsning 😄
