### ISSUE TITLE
Kan ikke bla tilbake i artikkellisten

### ISSUE THREAD

**Issue by vetlemangrud** [readme-ntnu/readme-arkiv#32]
https://readme.abakus.no/articles
Kan ikke bla tilbake i artikkellisten i admin-verktøyene. Blir bare en evig lasteskjerm.
Ser også ut som at masse artikler fra 01-2020 ikke vises, men kan være de ikke er lagt inn i det hele tatt

**Comment by AndreasHaaversen** [comment]
Godt issue! 😄 

*Problemer funnet:*
1. Viste seg at det manglet en index i Firestore, som førte til at det ikke var mulig å bla bakover i lista. 💥 
2. Query-et som driver pagineringen i lista så kun på utgave når den skulle bevege seg igennomlisten, noe som er ambiguøst når flere artikler naturlig nok tilhører samme utgave. 🤔

*Løsninger:*
1. Genererte index-en. 📜  
2. Oppdaterte query-et til å også ta hensyn til artiklenes sidetall, slik at query-et blir tilstrekkelig spesifikt for at pagineringen skal fungere som den skal. 👨‍💻 

Alt er blitt deploy-et til Firebase i skrivende stund. 🚀
